name: Build

# TODO: See if we can speed up the xcodebuild command

# TODO: See if we can cache realm cli as it takes 2 minutes to install

# Will need to expand this to other branches
on: [push, pull_request]

jobs:    
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
#     Setting env vars based on https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable      
    - name: "Are we pushing to the Main branch?"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: | 
           echo "REALM_APP_ID=inventorysync-ctnnu" >> $GITHUB_ENV
#           echo "IS_DYNAMICALLY_GENERATED_APP=false" >> $GITHUB_ENV
    - name: "Are we pushing to the Staging branch?"
      if: ${{ github.ref == 'refs/heads/staging' }}
      run: | 
           echo "REALM_APP_ID=inventorydemo-staging-zahjj" >> $GITHUB_ENV
#           echo "IS_DYNAMICALLY_GENERATED_APP=false" >> $GITHUB_ENV
# For Pull Requests, update the database name to be a unique name based on the current date and time
# Also, set the environment to be the Testing envrionment
    - name: "Set environment variables for all other runs"
      if: ${{ !env.REALM_APP_ID }}
      run: | 
           cd inventory/export/sync/environments
           time=$(date +%s%N)
           printf '{\n     "values": {"databaseName": "InventoryDemo-%s"}\n}' "$time" > testing.json     
           cd ..
           sed -i txt 's/{/{ "environment": "testing",/' realm_config.json 
           echo "IS_DYNAMICALLY_GENERATED_APP=true" >> $GITHUB_ENV
    - name: "Install the Realm CLI"
      run: npm install -g mongodb-realm-cli@beta
# Adding --realm-url and --atlas-url to login command to workaround authentication error           
    - name: "Authenticate to the Realm CLI (using generic API key)"
      if: ${{ env.REALM_APP_ID }}
      run: realm-cli login --api-key="${{ secrets.REALM_API_PUBLIC_KEY }}" --private-api-key="${{ secrets.REALM_API_PRIVATE_KEY }}" --realm-url https://realm.mongodb.com --atlas-url https://cloud.mongodb.com
# Making these separate steps since specifying the project id isn't working so we need to use separate API keys
# Need to think through splitting this for Dev pushes
    - name: "Authenticate to the Realm CLI (using API key for Testing Project)"
      if: ${{ env.IS_DYNAMICALLY_GENERATED_APP }}
      run: realm-cli login --api-key="${{ secrets.REALM_API_TESTING_PROJECT_PUBLIC_KEY }}" --private-api-key="${{ secrets.REALM_API_TESTING_PROJECT_PRIVATE_KEY }}" --realm-url https://realm.mongodb.com --atlas-url https://cloud.mongodb.com
    - name: "Push updated copy of the Realm app (Staging or Main branch)"
      if: ${{ env.REALM_APP_ID }}
      run: | 
           cd inventory/export/sync
           realm-cli push --remote="${{ env.REALM_APP_ID }}" -y
    - name: "Create a new Realm app for pull requests"
      if: ${{ env.IS_DYNAMICALLY_GENERATED_APP }}
      run: |
           cd inventory/export/sync
           realm-cli push -y
           output=$(realm-cli app describe)
           app_id=$(echo $output | sed 's/^.*client_app_id": "\([^"]*\).*/\1/')
           echo "REALM_APP_ID=$app_id" >> $GITHUB_ENV
           
#     - name: "Build mobile app & run tests"
#       run: |
#            echo "the realm app id is: $REALM_APP_ID"
#            cd inventory/clients/ios-swiftui/InventoryDemo
#            xcodebuild -project InventoryDemo.xcodeproj -scheme "ci" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.4' -derivedDataPath './output' REALM_APP_ID='${{ env.REALM_APP_ID }}' test
# Could choose to skip deleting apps where tests fail so you could manually investigate
# Not currently working due to a bug in the realm-cli
#     - name: "Delete dynamically generated Realm app"
#       if: ${{ env.IS_DYNAMICALLY_GENERATED_APP }}
#       run: realm-cli app delete -a $REALM_APP_ID

# TODO: test that this doesn't run if tests fail
    - name: "Push commits to the Main branch"
      if: ${{ github.ref == 'refs/heads/staging' }}
      run: |
           git branch
           git remote show origin
           git checkout master;
           git merge origin/staging;
           git push origin master;

