name: Build

# TODO: See if we can speed up the xcodebuild command

# Will need to expand this to other branches
on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:    
  build:
    runs-on: macos-latest
    steps:
#     - uses: actions/checkout@v2
#     Setting env vars based on https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable      
    - name: "Are we in Main branch?"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: | 
           echo "REALM_APP_ID=inventorysync-ctnnu" >> $GITHUB_ENV
           echo "We are in the main branch $REALM_APP_ID "
    - name: "Are we in Lauren's dev branch?"
      if: ${{ github.ref == 'refs/heads/lauren-dev' }}
      run: | 
           echo "REALM_APP_ID=lauren-dev-pjiuk" >> $GITHUB_ENV
           echo "We are in Lauren's dev branch $REALM_APP_ID "
    - name: "Test env vars"
      run: |
           echo ${{ env.REALM_APP_ID }}
           echo "the realm app id is: $REALM_APP_ID"
#     - name: Build
#       run: |
#            pwd
#            echo ${{ env.TEST_ID }}
#            echo "the test app id is: $TEST_ID"
#            echo ${{ env.REALM_APP_ID }}
#            echo "the realm app id is: $REALM_APP_ID"
#            cd inventory/clients/ios-swiftui/InventoryDemo
#           xcodebuild -project InventoryDemo.xcodeproj -scheme "ci" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.4' -derivedDataPath './output' REALM_APP_ID='${{ env.REALM_APP_ID }}' 
