name: Build

# TODO: See if we can speed up the xcodebuild command

# TODO: See if we can cache realm cli as it takes 2 minutes to install

# Will need to expand this to other branches
on: [push, pull_request]

jobs:    
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
#     Setting env vars based on https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable      
    - name: "Are we in the Main branch?"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: | 
           echo "REALM_APP_ID=inventorysync-ctnnu" >> $GITHUB_ENV
           echo "We are in the main branch $REALM_APP_ID "
    - name: "Are we in Lauren's dev branch?"
      if: ${{ github.ref == 'refs/heads/lauren-dev' || github.head_ref == 'lauren-dev' }}
      run: | 
           echo "REALM_APP_ID=lauren-dev-pjiuk" >> $GITHUB_ENV
           echo "We are in Lauren's dev branch $REALM_APP_ID "
    - name: "Test env vars"
      run: |
           echo ${{ env.REALM_APP_ID }}
           echo "the realm app id is: $REALM_APP_ID"
           echo ${{ github.ref }}
           echo ${{ github.head_ref }}
    - name: "Install Realm CLI & push the Realm app"
      run: | 
           npm install -g mongodb-realm-cli@beta
           pwd
           cd inventory/export/sync
           realm-cli push --remote="${{ env.REALM_APP_ID }}"
#     - name: "Build mobile app & run tests"
#       run: |
#            echo ${{ env.REALM_APP_ID }}
#            echo "the realm app id is: $REALM_APP_ID"
#            cd inventory/clients/ios-swiftui/InventoryDemo
#           xcodebuild -project InventoryDemo.xcodeproj -scheme "ci" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.4' -derivedDataPath './output' REALM_APP_ID='${{ env.REALM_APP_ID }}' 
