name: Build

# TODO: See if we can speed up the xcodebuild command

# TODO: See if we can cache realm cli as it takes 2 minutes to install

# Will need to expand this to other branches
on: [push, pull_request]

jobs:    
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
#     Setting env vars based on https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable      
    - name: "Are we in the Main branch?"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: | 
           echo "REALM_APP_ID=inventorysync-ctnnu" >> $GITHUB_ENV
           echo "We are in the main branch $REALM_APP_ID "
    - name: "Are we in Lauren's dev branch?"
      if: ${{ github.ref == 'refs/heads/lauren-dev' || github.head_ref == 'lauren-dev' }}
      run: | 
           echo "REALM_APP_ID=lauren-dev-pjiuk" >> $GITHUB_ENV
           echo "We are in Lauren's dev branch $REALM_APP_ID "
    - name: "Test env vars"
      run: |
           echo ${{ env.REALM_APP_ID }}
           echo "the realm app id is: $REALM_APP_ID"
           echo ${{ github.ref }}
           echo ${{ github.head_ref }}
# Adding --realm-url and --atlas-url to login command to workaround authentication error           
    - name: "Install the Realm CLI & authenticate (generic api key)"
      if: ${{ env.REALM_APP_ID }}
      run: | 
           npm install -g mongodb-realm-cli@beta
           realm-cli login --api-key="${{ secrets.REALM_API_PUBLIC_KEY }}" --private-api-key="${{ secrets.REALM_API_PRIVATE_KEY }}" --realm-url https://realm.mongodb.com --atlas-url https://cloud.mongodb.com
# Making these separate steps since specifying the project id isn't working so we need to use separate API keys
    - name: "Install the Realm CLI & authenticate (Testing Project api key)"
      if: ${{ !env.REALM_APP_ID }}
      run: | 
           npm install -g mongodb-realm-cli@beta
           realm-cli login --api-key="${{ secrets.REALM_API_TESTING_PROJECT_PUBLIC_KEY }}" --private-api-key="${{ secrets.REALM_API_TESTING_PROJECT_PRIVATE_KEY }}" --realm-url https://realm.mongodb.com --atlas-url https://cloud.mongodb.com
    - name: "Push updated copy of the Realm app if we have the Realm App ID"
      if: ${{ env.REALM_APP_ID }}
      run: | 
           cd inventory/export/sync
           realm-cli push --remote="${{ env.REALM_APP_ID }}"
    - name: "Create a new Realm app for pull requests where the Realm app does not yet exist"
      if: ${{ !env.REALM_APP_ID }}
      run: |
           echo "The env variable is not set"
           cd inventory/export/sync
           realm-cli import -y
           output=$(realm-cli app describe)
           echo "$output"
           app_id=$(echo $output | sed 's/^.*client_app_id": "\([^"]*\).*/\1/')
           echo "$app_id"
           echo "REALM_APP_ID=$app_id" >> $GITHUB_ENV
           echo ${{ env.REALM_APP_ID }}
           echo "REALM_APP_ID=${{ env.REALM_APP_ID }}" >> $GITHUB_ENV
           echo ${{ env.REALM_APP_ID }}
           echo "IS_TESTING_APP=true" >> $GITHUB_ENV
           echo ${{ env.IS_TESTING_APP }}
    - name: "Build mobile app & run tests"
      run: |
           echo ${{ env.REALM_APP_ID }}
           echo "the realm app id is: $REALM_APP_ID"
           cd inventory/clients/ios-swiftui/InventoryDemo
           xcodebuild -project InventoryDemo.xcodeproj -scheme "ci" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.45' -derivedDataPath './output' REALM_APP_ID='${{ env.REALM_APP_ID }}' test
# TODO: Delete apps where IS_TESTING_APP
