name: Build

# TODO: See if we can speed up the xcodebuild command

# Will need to expand this to other branches
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#   setup: 
#     runs-on: macos-latest
#     steps:
#     - name: "Define Realm APP Id"
#       if: ${{ github.ref == 'refs/heads/main' }}
#       run: echo "We are in the main branch $REALM_APP_ID "
#       env:
#          REALM_APP_ID: inventorysync-ctnnu
    
  build:
#     needs: setup
    runs-on: macos-latest
    env:
        TEST_ID: hello-lauren

    steps:
#     - uses: actions/checkout@v2
    - name: "Define Realm APP Id"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: | 
           echo "::set-env $REALM_APP_ID=DAY_OF_WEEK::inventorysync-ctnnu"
           echo "We are in the main branch $REALM_APP_ID "
    - name: "Test env vars"
      run: |
           echo ${{ env.TEST_ID }}
           echo "the test app id is: $TEST_ID"
           echo ${{ env.REALM_APP_ID }}
           echo "the realm app id is: $REALM_APP_ID"
#     - name: Build
#       run: |
#            pwd
#            echo ${{ env.TEST_ID }}
#            echo "the test app id is: $TEST_ID"
#            echo ${{ env.REALM_APP_ID }}
#            echo "the realm app id is: $REALM_APP_ID"
#            cd inventory/clients/ios-swiftui/InventoryDemo
#           xcodebuild -project InventoryDemo.xcodeproj -scheme "ci" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=14.4' -derivedDataPath './output' REALM_APP_ID='${{ env.REALM_APP_ID }}' 
# Will need to deploy the app using realm cli first      
#    - name: Run tests
#      run: swift test -v
